### ISSUE TITLE
Gallery

### ISSUE THREAD

**Issue by Andrews54757** [AJS-development/OpenAgarClient#1]
(The playcells have a mass of 100)

Old Client:
<img width="1279" alt="screen shot 2017-05-05 at 3 50 04 pm" src="https://cloud.githubusercontent.com/assets/13282284/25761928/9e4eb188-31aa-11e7-8049-08cc6d8ebb88.png">

New Client
<img width="1244" alt="screen shot 2017-05-05 at 10 17 21 am" src="https://cloud.githubusercontent.com/assets/13282284/25749314/1739b4c8-317c-11e7-85fb-56ef37e2fdb5.png">

4 Hours Later:

<img width="1270" alt="screen shot 2017-05-05 at 3 47 46 pm" src="https://cloud.githubusercontent.com/assets/13282284/25761874/5cd30c18-31aa-11e7-9a4e-27d54d00ac48.png">

One Week Later:

<img width="1277" alt="screen shot 2017-05-14 at 7 40 52 pm" src="https://cloud.githubusercontent.com/assets/13282284/26038774/de188f66-38dd-11e7-9d9c-db1e705dd410.png">

Two weeks later:

![screen shot 2017-05-25 at 8 34 51 am](https://cloud.githubusercontent.com/assets/13282284/26450379/1b5bd582-4125-11e7-96de-567708c154ef.png)

One Month later:

![screen shot 2017-06-08 at 10 00 34 pm](https://user-images.githubusercontent.com/13282284/26957951-1142c868-4c96-11e7-9b71-735ca018a9ff.png)

Another week later:

<img width="1005" alt="screen shot 2017-06-19 at 5 15 14 pm" src="https://user-images.githubusercontent.com/13282284/27306245-ebc536cc-5512-11e7-8b8f-cd06c7c6f24e.png">

A few days later:

![screen shot 2017-06-21 at 10 17 14 pm](https://user-images.githubusercontent.com/13282284/27414449-776f0848-56cf-11e7-957b-a7b5d7675b93.png)

**Comment by LegitSoulja** [comment]
![capture](https://cloud.githubusercontent.com/assets/4976824/25771575/ab7f4ede-3223-11e7-9dd0-2078a043de2e.PNG)

Made MAJOR improvements.

**Comment by LegitSoulja** [comment]
I was wondering why the edges was so ridged, figured out you weren't using textures.

**Comment by Andrews54757** [comment]
@LegitSoulja I was using graphics because I think it is faster. I was thinking of removing the fuss at the borders via the animation that we will make later.

**Comment by LegitSoulja** [comment]
@Andrews54757 hm, shall I revert those changes then?

**Comment by LegitSoulja** [comment]
@Andrews54757 Leaderboard is complete, except for teams.

**Comment by LegitSoulja** [comment]
Chat also needs to be done, you did it last time, i'll leave it in your hands

**Comment by Andrews54757** [comment]
Ok

**Comment by Andrews54757** [comment]
(BTW, we need to do viruses)

**Comment by Andrews54757** [comment]
@LegitSoulja Mabye we need to do the chatbox from HTML. Because otherwise: https://github.com/pixijs/pixi.js/issues/821.


BTW: the old client uses HTML

**Comment by LegitSoulja** [comment]
@Andrews54757 I can make a custom chat box... It doesn't have to be an input/HTML type content. 

I've read that an input overlaps the canvas, but I don't think that's a good way. So.. I think it's best to make something custom.

**Comment by LegitSoulja** [comment]
And yes, the old client has an HTML input, but that issue was 3 years ago. Things work, as of what I've tested.

**Comment by LegitSoulja** [comment]
@Andrews54757 check this out https://github.com/AJS-development/OpenAgarClient/commit/97998e788a6e9ed3e0866fa15cc9d5d7faa0226b

Now, just the actual chat log needs to be done.

**Comment by Codeidiot737** [comment]
Doesn't the initial scale, maximum scale, and user-scalable need to be separated by camas instead of ;?

**Comment by LegitSoulja** [comment]
@Codeidiot737 and could you not fork this project? Thanks.

**Comment by LegitSoulja** [comment]
Well, nvm we won't release a working client. This will be deleted eventually.

**Comment by Codeidiot737** [comment]
why

**Comment by LegitSoulja** [comment]
This is only for a tasked/collaboration development work session (Me/Andrew). There will be no public client release. Meaning, our work that is being put into our client/server is only dedicated for our project OpenAgar. 

All rights are reserved, as we claim all ownership over our work.

**Comment by Codeidiot737** [comment]
:(, i just want to watch, learn, and eventually help in future projects.

**Comment by LegitSoulja** [comment]
However, if you're interested in making a pixi game, our code can be helpful for future use of your own time of development.

**Comment by LegitSoulja** [comment]
Yes you can do that, no problem. But I was just being cautious on how known this project may get.

**Comment by Codeidiot737** [comment]
don't worry, it will stay as you want it

**Comment by LegitSoulja** [comment]
Once someone hears about a client they'll never stop asking for it. That's just like you asking YouTube/Facebook for their site. And there's security aswell between our server/client for secure/legal gameplay. 

So you can understand how secure we have to take things. It just won't be possible for multiple client uses. Too much work on our hand, besides. We wanted a client, so we are making it. If someone wants one, it shouldn't be as hard if they really wanted it. 

We don't give away cookies, but we'll give you milk for the thirst.

**Comment by LegitSoulja** [comment]
@Codeidiot737 and lol why'd you delete your message? What about the scaling?

**Comment by Codeidiot737** [comment]
**@LegitSoulja** sry, I am a friend of Andrew54757. And: 
Key "initial-scale" "maximum-scale" and "user-scalable" was truncated to its numeric prefix.  ';' is not a separator in viewport values. The list should be comma-separated.

**Comment by Codeidiot737** [comment]
hm, my last reply didnt send

**Comment by Andrews54757** [comment]
@LegitSoulja It doesnt matter in this stage yet... We havent put in the sensitive info yet.

**Comment by LegitSoulja** [comment]
@Codeidiot737 Oh, I'll get to that eventually. I don't think we will need it.

**Comment by LegitSoulja** [comment]
And mobile wont be supported as of yet. So there's no need right now.

**Comment by LegitSoulja** [comment]
@Codeidiot737 and yea, I been knew that. I added that fix a year ago, on our old client http://old.ogarul.io

**Comment by fayizan** [comment]
WoW I m waiting :)

**Comment by LegitSoulja** [comment]
I  might remake the UI, I got a better idea. 

Bye bye skin selector, and skin search.

**Comment by SAVAGE2001** [comment]
i'm really excited

**Comment by Andrews54757** [comment]
UPDATE:

Mesh Code complete! (Collision animation)

<img width="1142" alt="screen shot 2017-05-21 at 5 56 41 pm" src="https://cloud.githubusercontent.com/assets/13282284/26287812/757b2d42-3e50-11e7-8f35-b69cd88ed714.png">

**Comment by LegitSoulja** [comment]
@Andrews54757 

Here's the idea with the CORS.

All skins will be hosted, from opnagar.us, in which `home` authentications is needed for others to upload skins via the client. It's possible we can sync custom skins from servers, and download them, (Only with `home` authentication). 

Reasons of authentications, is we can easily manage per user skin, and allow them to manage each of their skin to rename/delete/disable etc. 

Skin re-naming will be put on hold for approvals. Basically, there will be a custom gallery, not hosted via the forum. Reasons why not the forum, eh because the page issue is inefficient, and the skins/ids aren't self managed. If a skin for example, gets updated, and or deleted the entire skin list id's will have an offset, giving incorrect skin id's. Anyways, I need to make a self automatic skin manager, in which is a gallery, which will have it's own site/panel.

**Comment by LegitSoulja** [comment]
- **edit**

Let's separate the UI/Forum logins, from the skins entirely. I'll just make another login system.

**Comment by Andrews54757** [comment]
UPDATE: (socket now working)

<img width="1280" alt="screen shot 2017-06-03 at 7 43 00 pm" src="https://cloud.githubusercontent.com/assets/13282284/26757734/f0d43a76-4894-11e7-958e-3eae8d668f81.png">

**Comment by Andrews54757** [comment]
UPDATE: Skins now done!

![screen shot 2017-06-08 at 8 53 22 pm](https://user-images.githubusercontent.com/13282284/26956547-9d23ae60-4c8c-11e7-8f34-a143174d6ff1.png)

**Comment by Andrews54757** [comment]
UPDATE: FInished chat!

![screen shot 2017-06-21 at 12 28 17 pm](https://user-images.githubusercontent.com/13282284/27395276-42c547f8-567d-11e7-949c-5d048a1087b3.png)

**Comment by fayizan** [comment]
lol 7.5 fps, Seems Client gonna be up next week right ?

**Comment by fayizan** [comment]
add agarplus theme as an option ?

**Comment by segg21** [comment]
@fayizan was supposed to been released but there's a few things need to be done, and Andrew is currently on vacation.

And agarplus theme? I'd rather make the entire game/ui customizable.

**Comment by segg21** [comment]
^ But we aren't pushing a lot in beta. This is extra that'll be done out of beta. Out of beta, accounts will exist. Hopefully. It's needed if its customizable.

**Comment by Faris90** [comment]
RIP openagar
